In [1]:
%load_ext autoreload
%autoreload 2

from datetime import datetime
from scraiping import Scraiping
from complete import Complete
from train import Tree_updown, Tree_updown_k

In [14]:
start = datetime(2010, 1, 1)
finish = datetime(2020, 5, 17)

target_number = '2432' #(株)DeNA
prepare_number = ['1309', #上海株式指数・上証50連動型上場投資信託
                '1325', #(NEXT FUNDS)ブラジル株式指数上場投信
                '1326', #SPDRゴールド･シェア
                '1377', #サカタのタネ
                '1465', #ダイワ上場投信-JPX日経400インバース
                '1633', #(NEXT FUNDS)不動産上場投信
                '1678', #(NEXT FUNDS)インド株式指数上場投信
                '1698', #上場インデックスファンド日本高配当
                ]

headers = {'User-Agent' : 'Please write your User-Agent'}

max_depth = 5
test_size = 0.25
k = 2

In [3]:
# スクレイピング
stock_numbers = prepare_number.copy()
stock_numbers.insert(0, target_number)
dfs = Scraiping(stock_numbers, start, finish, headers).main()

Done : 4751
Done : 1309
Done : 1325
Done : 1326
Done : 1377
Done : 1465
Done : 1633
Done : 1678
Done : 1698

In [4]:
# 機械学習するためにデータを処理する
complete_df = Complete(dfs, stock_numbers).com()
complete_df

,Date,4751,4751_Diff,1309,1309_Diff,1325,1325_Diff,1326,1326_Diff,1377,1377_Diff,1465,1465_Diff,1633,1633_Diff,1678,1678_Diff,1698,1698_Diff
0,2015-08-24,4685,-0.068588,30500,-0.071537,135,-0.042553,13430,-0.020423,1911,-0.047833,10580,NaN,32750,-0.076164,133,-0.069930,1617,-0.052169
1,2015-08-25,4890,0.043757,28920,-0.051803,130,-0.037037,13160,-0.020104,1845,-0.034537,10920,0.032136,31850,-0.027481,127,-0.045113,1560,-0.035250
2,2015-08-26,4820,-0.014315,30200,0.044260,129,-0.007692,13040,-0.009119,1873,0.015176,10590,-0.030220,32400,0.017268,132,0.039370,1600,0.025641
3,2015-08-27,4745,-0.015560,30700,0.016556,133,0.031008,12950,-0.006902,1916,0.022958,10440,-0.014164,32950,0.016975,132,0.000000,1607,0.004375
4,2015-08-28,4955,0.044257,32450,0.057003,138,0.037594,13130,0.013900,1953,0.019311,10120,-0.030651,33750,0.024279,136,0.030303,1667,0.037337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,2020-05-08,4520,-0.010941,32300,0.012539,119,0.025862,17190,0.017160,3640,0.016760,7480,-0.019659,23890,0.027527,120,0.000000,1378,0.015475
915,2020-05-11,4435,-0.018805,32200,-0.003096,122,0.025210,17140,-0.002909,3600,-0.010989,7350,-0.017380,25020,0.047300,122,0.016667,1413,0.025399
916,2020-05-12,4495,0.013529,32150,-0.001553,120,-0.016393,17170,0.001750,3650,0.013889,7370,0.002721,24200,-0.032774,118,-0.032787,1404,-0.006369
917,2020-05-13,4690,0.043382,31900,-0.007776,121,0.008333,17190,0.001165,3700,0.013699,7430,0.008141,24200,0.000000,120,0.016949,1397,-0.004986
918,2020-05-14,4700,0.002132,31650,-0.007837,119,-0.016529,17220,0.001745,3640,-0.016216,7510,0.010767,23790,-0.016942,119,-0.008333,1372,-0.017895

In [13]:
# ただ単に株価が上下するかどうか
tu = Tree_updown(complete_df, stock_numbers, test_size, max_depth)
X, y = tu.prepare()
tu.predict(X, y)

predict next day : DOWN

テスト用正解率:0.4956521739130435
学習用正解率:0.6390101892285298

  feature_names  coefficient
0          4751     0.079317
1          1309     0.295975
2          1325     0.119922
3          1326     0.060214
4          1377     0.226532
5          1465     0.000000
6          1633     0.072541
7          1678     0.114291
8          1698     0.031207

データ数:917

In [15]:
# 上下何％で株価が上下するかどうか。kで設定する。
tu_k = Tree_updown_k(complete_df, stock_numbers, test_size, max_depth, k)
X, y = tu_k.prepare_k()
tu_k.predict(X, y)

predict next day : CONSTANT

テスト用正解率:0.591304347826087
学習用正解率:0.6317321688500728

  feature_names  coefficient
0          4751     0.160904
1          1309     0.000000
2          1325     0.141786
3          1326     0.000000
4          1377     0.356749
5          1465     0.000000
6          1633     0.089495
7          1678     0.175456
8          1698     0.075611

データ数:917